export const ADD_STATE = 'ADD_STATE';
export const ADD_CONTEXT_VARIABLE = 'ADD_CONTEXT_VARIABLE';
export const ADD_PLATFORM = 'ADD_PLATFORM';
export const ADD_NAME = 'ADD_NAME';
export const ADD_PARAMETER = 'ADD_PARAMETER';
export const ADD_ACTION = 'ADD_ACTION';
export const ADD_TRANSITION = 'ADD_TRANSITION';

export const RENAME_STATE = 'RENAME_STATE';
export const RENAME_CONTEXT_VARIABLE = 'RENAME_CONTEXT_VARIABLE';
export const RENAME_PLATFORM = 'RENAME_PLATFORM';
export const RENAME_NAME = 'RENAME_NAME';
export const RENAME_PARAMETER = 'RENAME_PARAMETER';

export const REMOVE_STATE = 'REMOVE_STATE';
export const REMOVE_CONTEXT_VARIABLE = 'REMOVE_CONTEXT_VARIABLE';
export const REMOVE_PLATFORM = 'REMOVE_PLATFORM';
export const REMOVE_NAME = 'REMOVE_NAME';
export const REMOVE_PARAMETER = 'REMOVE_PARAMETER';
export const REMOVE_ACTION = 'REMOVE_ACTION';