export const MAP_NODE_TO_POSITION = 'MAP_NODE_TO_POSITION';
export const MAP_NODE_NAME_TO_ID = 'MAP_NODE_NAME_TO_ID';
export const MAP_PORT_NAME_TO_ID = 'MAP_PORT_NAME_TO_ID';
export const MAP_LINK_TO_NODE_PAIR = 'MAP_LINK_TO_NODE_PAIR';

export const MARK_ID_INVISIBLE = 'MARK_ID_INVISIBLE';
export const MARK_ID_VISIBLE = 'MARK_ID_VISIBLE';

export const UNMAP_NAME_TO_ID = 'UNMAP_NAME_TO_ID';

export const SET_SELECTED_LINK = 'SET_SELECTED_LINK';